version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    env_file:
      - database.env # configure postgres
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
